// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestUIBanHang
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// BanHangTest - Use 'BanHangTestParams' to pass parameters into this method.
        /// </summary>
        public void BanHangTest()
        {
            #region Variable Declarations
            WinEdit uITxtTaiKhoanEdit = this.UIFrmDangNhapWindow.UIUsernameWindow.UITxtTaiKhoanEdit;
            WinClient uIFrmDangNhapClient = this.UIFrmDangNhapWindow.UIFrmDangNhapClient;
            WinEdit uITxtMatKhauEdit = this.UIFrmDangNhapWindow.UIPasswordWindow.UITxtMatKhauEdit;
            WinButton uIĐăngnhậpButton = this.UIFrmDangNhapWindow.UIĐăngnhậpWindow.UIĐăngnhậpButton;
            WinButton uIBánHàngButton = this.UIBánHàngWindow.UIBánHàngButton;
            WinComboBox uICboSanPhamComboBox = this.UIBánhàngWindow.UICboSanPhamWindow.UICboSanPhamComboBox;
            WinComboBox uICbSoLuongComboBox = this.UIBánhàngWindow.UICbSoLuongWindow.UICbSoLuongComboBox;
            WinButton uITHÊMVÀOGIỎButton = this.UIBánhàngWindow.UITHÊMVÀOGIỎWindow.UITHÊMVÀOGIỎButton;
            WinComboBox uICbKhachHangComboBox = this.UIBánhàngWindow.UICbKhachHangWindow.UICbKhachHangComboBox;
            WinButton uITẠMTÍNHButton = this.UIBánhàngWindow.UITẠMTÍNHWindow.UITẠMTÍNHButton;
            WinEdit uITxtKhachThanhToanEdit = this.UIBánhàngWindow.UIItem0Window.UITxtKhachThanhToanEdit;
            WinButton uIKháchĐưaĐủButton = this.UIFrm_ChonTienWindow.UIKháchĐưaĐủWindow.UIKháchĐưaĐủButton;
            #endregion

            // Type 'QL003' in 'txtTaiKhoan' text box
            uITxtTaiKhoanEdit.Text = this.BanHangTestParams.UITxtTaiKhoanEditText;

            // Click 'frmDangNhap' client
            Mouse.Click(uIFrmDangNhapClient, new Point(153, 287));

            // Click 'txtMatKhau' text box
            Mouse.Click(uITxtMatKhauEdit, new Point(47, 14));

            // Type '{NumPad1}{NumPad2}{NumPad3}' in 'txtMatKhau' text box
            Keyboard.SendKeys(uITxtMatKhauEdit, this.BanHangTestParams.UITxtMatKhauEditSendKeys, ModifierKeys.None);

            // Click 'Đăng nhập' button
            Mouse.Click(uIĐăngnhậpButton, new Point(96, 14));

            // Click 'Bán Hàng' button
            Mouse.Click(uIBánHàngButton, new Point(103, 32));

            // Select 'White conc' in 'cboSanPham' combo box
            uICboSanPhamComboBox.SelectedItem = this.BanHangTestParams.UICboSanPhamComboBoxSelectedItem;

            // Select '2' in 'cbSoLuong' combo box
            uICbSoLuongComboBox.SelectedItem = this.BanHangTestParams.UICbSoLuongComboBoxSelectedItem;

            // Click 'THÊM VÀO GIỎ' button
            Mouse.Click(uITHÊMVÀOGIỎButton, new Point(146, 21));

            // Select 'Lê Vĩnh Khiêm' in 'cbKhachHang' combo box
            uICbKhachHangComboBox.SelectedItem = this.BanHangTestParams.UICbKhachHangComboBoxSelectedItem;

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(19, 17));

            // Click 'txtKhachThanhToan' text box
            Mouse.Click(uITxtKhachThanhToanEdit, new Point(39, 6));

            // Click 'Khách Đưa Đủ' button
            Mouse.Click(uIKháchĐưaĐủButton, new Point(229, 24));

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(68, 30));
        }
        
        /// <summary>
        /// TestLan2 - Use 'TestLan2Params' to pass parameters into this method.
        /// </summary>
        public void TestLan2()
        {
            #region Variable Declarations
            WinComboBox uICboSanPhamComboBox = this.UIBánhàngWindow.UICboSanPhamWindow.UICboSanPhamComboBox;
            WinComboBox uICbSoLuongComboBox = this.UIBánhàngWindow.UICbSoLuongWindow.UICbSoLuongComboBox;
            WinButton uITHÊMVÀOGIỎButton = this.UIBánhàngWindow.UITHÊMVÀOGIỎWindow.UITHÊMVÀOGIỎButton;
            WinComboBox uICbKhachHangComboBox = this.UIBánhàngWindow.UICbKhachHangWindow.UICbKhachHangComboBox;
            WinButton uITẠMTÍNHButton = this.UIBánhàngWindow.UITẠMTÍNHWindow.UITẠMTÍNHButton;
            WinEdit uITxtKhachThanhToanEdit = this.UIBánhàngWindow.UIItem0Window.UITxtKhachThanhToanEdit;
            WinButton uIKháchĐưaĐủButton = this.UIFrm_ChonTienWindow.UIKháchĐưaĐủWindow.UIKháchĐưaĐủButton;
            WinButton uITẠOHÓAĐƠNXUẤTBILLButton = this.UIBánhàngWindow.UITẠOHÓAĐƠNXUẤTBILLWindow.UITẠOHÓAĐƠNXUẤTBILLButton;
            WinButton uICloseButton = this.UIFrm_HoaDonWindow.UIFrm_HoaDonTitleBar.UICloseButton;
            #endregion

            // Select 'White conc' in 'cboSanPham' combo box
            uICboSanPhamComboBox.SelectedItem = this.TestLan2Params.UICboSanPhamComboBoxSelectedItem;

            // Select '3' in 'cbSoLuong' combo box
            uICbSoLuongComboBox.SelectedItem = this.TestLan2Params.UICbSoLuongComboBoxSelectedItem;

            // Click 'THÊM VÀO GIỎ' button
            Mouse.Click(uITHÊMVÀOGIỎButton, new Point(112, 30));

            // Select 'Nguyễn Quang Huy' in 'cbKhachHang' combo box
            uICbKhachHangComboBox.SelectedItem = this.TestLan2Params.UICbKhachHangComboBoxSelectedItem;

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(47, 7));

            // Click 'txtKhachThanhToan' text box
            Mouse.Click(uITxtKhachThanhToanEdit, new Point(84, 6));

            // Click 'Khách Đưa Đủ' button
            Mouse.Click(uIKháchĐưaĐủButton, new Point(274, 22));

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(70, 17));

            // Click 'TẠO HÓA ĐƠN && XUẤT BILL' button
            Mouse.Click(uITẠOHÓAĐƠNXUẤTBILLButton, new Point(51, 15));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(19, 11));
        }
        
        /// <summary>
        /// TestBuoc1 - Use 'TestBuoc1Params' to pass parameters into this method.
        /// </summary>
        public void TestBuoc1()
        {
            #region Variable Declarations
            WinComboBox uICboSanPhamComboBox = this.UIBánhàngWindow.UICboSanPhamWindow.UICboSanPhamComboBox;
            WinComboBox uICbSoLuongComboBox = this.UIBánhàngWindow.UICbSoLuongWindow.UICbSoLuongComboBox;
            WinButton uITHÊMVÀOGIỎButton = this.UIBánhàngWindow.UITHÊMVÀOGIỎWindow.UITHÊMVÀOGIỎButton;
            WinButton uITẠMTÍNHButton = this.UIBánhàngWindow.UITẠMTÍNHWindow.UITẠMTÍNHButton;
            WinComboBox uICbKhachHangComboBox = this.UIBánhàngWindow.UICbKhachHangWindow.UICbKhachHangComboBox;
            WinWindow uIItem0Window = this.UIBánhàngWindow.UIHóađơnGroup.UIItem0Window;
            WinEdit uITxtKhachThanhToanEdit = this.UIBánhàngWindow.UIItem0Window.UITxtKhachThanhToanEdit;
            WinButton uIKháchĐưaĐủButton = this.UIFrm_ChonTienWindow.UIKháchĐưaĐủWindow.UIKháchĐưaĐủButton;
            WinButton uITẠOHÓAĐƠNXUẤTBILLButton = this.UIBánhàngWindow.UITẠOHÓAĐƠNXUẤTBILLWindow.UITẠOHÓAĐƠNXUẤTBILLButton;
            WinButton uIXuấtBillButton = this.UIFrm_HoaDonWindow.UIXuấtBillWindow.UIXuấtBillButton;
            WinButton uICloseButton = this.UIFrm_HoaDonWindow.UIFrm_HoaDonTitleBar.UICloseButton;
            #endregion

            // Select 'White conc' in 'cboSanPham' combo box
            uICboSanPhamComboBox.SelectedItem = this.TestBuoc1Params.UICboSanPhamComboBoxSelectedItem;

            // Select '1' in 'cbSoLuong' combo box
            uICbSoLuongComboBox.SelectedItem = this.TestBuoc1Params.UICbSoLuongComboBoxSelectedItem;

            // Click 'THÊM VÀO GIỎ' button
            Mouse.Click(uITHÊMVÀOGIỎButton, new Point(92, 25));

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(83, 14));

            // Select 'Lê Vĩnh Khiêm' in 'cbKhachHang' combo box
            uICbKhachHangComboBox.SelectedItem = this.TestBuoc1Params.UICbKhachHangComboBoxSelectedItem;

            // Click '0' window
            Mouse.Click(uIItem0Window, new Point(82, 1));

            // Click 'txtKhachThanhToan' text box
            Mouse.Click(uITxtKhachThanhToanEdit, new Point(70, 7));

            // Click 'Khách Đưa Đủ' button
            Mouse.Click(uIKháchĐưaĐủButton, new Point(227, 16));

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(56, 26));

            // Click 'TẠO HÓA ĐƠN && XUẤT BILL' button
            Mouse.Click(uITẠOHÓAĐƠNXUẤTBILLButton, new Point(49, 23));

            // Click 'Xuất Bill' button
            Mouse.Click(uIXuấtBillButton, new Point(51, 8));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(24, 11));
        }
        
        /// <summary>
        /// Buoc1Test - Use 'Buoc1TestParams' to pass parameters into this method.
        /// </summary>
        public void Buoc1Test()
        {
            #region Variable Declarations
            WinComboBox uICboSanPhamComboBox = this.UIBánhàngWindow.UICboSanPhamWindow.UICboSanPhamComboBox;
            WinComboBox uICbSoLuongComboBox = this.UIBánhàngWindow.UICbSoLuongWindow.UICbSoLuongComboBox;
            WinButton uITHÊMVÀOGIỎButton = this.UIBánhàngWindow.UITHÊMVÀOGIỎWindow.UITHÊMVÀOGIỎButton;
            WinComboBox uICbKhachHangComboBox = this.UIBánhàngWindow.UICbKhachHangWindow.UICbKhachHangComboBox;
            WinButton uITẠMTÍNHButton = this.UIBánhàngWindow.UITẠMTÍNHWindow.UITẠMTÍNHButton;
            WinEdit uITxtKhachThanhToanEdit = this.UIBánhàngWindow.UIItem0Window.UITxtKhachThanhToanEdit;
            WinButton uIKháchĐưaĐủButton = this.UIFrm_ChonTienWindow.UIKháchĐưaĐủWindow.UIKháchĐưaĐủButton;
            WinButton uITẠOHÓAĐƠNXUẤTBILLButton = this.UIBánhàngWindow.UITẠOHÓAĐƠNXUẤTBILLWindow.UITẠOHÓAĐƠNXUẤTBILLButton;
            WinButton uICloseButton = this.UIFrm_HoaDonWindow.UIFrm_HoaDonTitleBar.UICloseButton;
            #endregion

            // Select 'White conc' in 'cboSanPham' combo box
            uICboSanPhamComboBox.SelectedItem = this.Buoc1TestParams.UICboSanPhamComboBoxSelectedItem;

            // Select '1' in 'cbSoLuong' combo box
            uICbSoLuongComboBox.SelectedItem = this.Buoc1TestParams.UICbSoLuongComboBoxSelectedItem;

            // Click 'THÊM VÀO GIỎ' button
            Mouse.Click(uITHÊMVÀOGIỎButton, new Point(190, 12));

            // Select 'Phan Thanh Hải' in 'cbKhachHang' combo box
            uICbKhachHangComboBox.SelectedItem = this.Buoc1TestParams.UICbKhachHangComboBoxSelectedItem;

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(48, 23));

            // Click 'txtKhachThanhToan' text box
            Mouse.Click(uITxtKhachThanhToanEdit, new Point(109, 12));

            // Click 'Khách Đưa Đủ' button
            Mouse.Click(uIKháchĐưaĐủButton, new Point(127, 32));

            // Click 'TẠM TÍNH' button
            Mouse.Click(uITẠMTÍNHButton, new Point(79, 7));

            // Click 'TẠO HÓA ĐƠN && XUẤT BILL' button
            Mouse.Click(uITẠOHÓAĐƠNXUẤTBILLButton, new Point(51, 15));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(31, 18));
        }
        
        /// <summary>
        /// TestValue - Use 'TestValueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestValue()
        {
            #region Variable Declarations
            WinEdit uITxtTienTraKhachEdit = this.UIBánhàngWindow.UIItem0Window1.UITxtTienTraKhachEdit;
            #endregion

            // Verify that the 'ControlType' property of 'txtTienTraKhach' text box is not equal to '0'
            Assert.AreNotEqual(this.TestValueExpectedValues.UITxtTienTraKhachEditControlType, uITxtTienTraKhachEdit.ControlType.ToString(), "Sai Roi Nha");
        }
        
        #region Properties
        public virtual BanHangTestParams BanHangTestParams
        {
            get
            {
                if ((this.mBanHangTestParams == null))
                {
                    this.mBanHangTestParams = new BanHangTestParams();
                }
                return this.mBanHangTestParams;
            }
        }
        
        public virtual TestLan2Params TestLan2Params
        {
            get
            {
                if ((this.mTestLan2Params == null))
                {
                    this.mTestLan2Params = new TestLan2Params();
                }
                return this.mTestLan2Params;
            }
        }
        
        public virtual TestBuoc1Params TestBuoc1Params
        {
            get
            {
                if ((this.mTestBuoc1Params == null))
                {
                    this.mTestBuoc1Params = new TestBuoc1Params();
                }
                return this.mTestBuoc1Params;
            }
        }
        
        public virtual Buoc1TestParams Buoc1TestParams
        {
            get
            {
                if ((this.mBuoc1TestParams == null))
                {
                    this.mBuoc1TestParams = new Buoc1TestParams();
                }
                return this.mBuoc1TestParams;
            }
        }
        
        public virtual TestValueExpectedValues TestValueExpectedValues
        {
            get
            {
                if ((this.mTestValueExpectedValues == null))
                {
                    this.mTestValueExpectedValues = new TestValueExpectedValues();
                }
                return this.mTestValueExpectedValues;
            }
        }
        
        public UIFrmDangNhapWindow UIFrmDangNhapWindow
        {
            get
            {
                if ((this.mUIFrmDangNhapWindow == null))
                {
                    this.mUIFrmDangNhapWindow = new UIFrmDangNhapWindow();
                }
                return this.mUIFrmDangNhapWindow;
            }
        }
        
        public UIBánHàngWindow UIBánHàngWindow
        {
            get
            {
                if ((this.mUIBánHàngWindow == null))
                {
                    this.mUIBánHàngWindow = new UIBánHàngWindow();
                }
                return this.mUIBánHàngWindow;
            }
        }
        
        public UIBánhàngWindow UIBánhàngWindow
        {
            get
            {
                if ((this.mUIBánhàngWindow == null))
                {
                    this.mUIBánhàngWindow = new UIBánhàngWindow();
                }
                return this.mUIBánhàngWindow;
            }
        }
        
        public UIThôngbáoWindow UIThôngbáoWindow
        {
            get
            {
                if ((this.mUIThôngbáoWindow == null))
                {
                    this.mUIThôngbáoWindow = new UIThôngbáoWindow();
                }
                return this.mUIThôngbáoWindow;
            }
        }
        
        public UIFrm_ChonTienWindow UIFrm_ChonTienWindow
        {
            get
            {
                if ((this.mUIFrm_ChonTienWindow == null))
                {
                    this.mUIFrm_ChonTienWindow = new UIFrm_ChonTienWindow();
                }
                return this.mUIFrm_ChonTienWindow;
            }
        }
        
        public UIFrm_HoaDonWindow UIFrm_HoaDonWindow
        {
            get
            {
                if ((this.mUIFrm_HoaDonWindow == null))
                {
                    this.mUIFrm_HoaDonWindow = new UIFrm_HoaDonWindow();
                }
                return this.mUIFrm_HoaDonWindow;
            }
        }
        #endregion
        
        #region Fields
        private BanHangTestParams mBanHangTestParams;
        
        private TestLan2Params mTestLan2Params;
        
        private TestBuoc1Params mTestBuoc1Params;
        
        private Buoc1TestParams mBuoc1TestParams;
        
        private TestValueExpectedValues mTestValueExpectedValues;
        
        private UIFrmDangNhapWindow mUIFrmDangNhapWindow;
        
        private UIBánHàngWindow mUIBánHàngWindow;
        
        private UIBánhàngWindow mUIBánhàngWindow;
        
        private UIThôngbáoWindow mUIThôngbáoWindow;
        
        private UIFrm_ChonTienWindow mUIFrm_ChonTienWindow;
        
        private UIFrm_HoaDonWindow mUIFrm_HoaDonWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'BanHangTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class BanHangTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'QL003' in 'txtTaiKhoan' text box
        /// </summary>
        public string UITxtTaiKhoanEditText = "QL003";
        
        /// <summary>
        /// Type '{NumPad1}{NumPad2}{NumPad3}' in 'txtMatKhau' text box
        /// </summary>
        public string UITxtMatKhauEditSendKeys = "{NumPad1}{NumPad2}{NumPad3}";
        
        /// <summary>
        /// Select 'White conc' in 'cboSanPham' combo box
        /// </summary>
        public string UICboSanPhamComboBoxSelectedItem = "White conc";
        
        /// <summary>
        /// Select '2' in 'cbSoLuong' combo box
        /// </summary>
        public string UICbSoLuongComboBoxSelectedItem = "2";
        
        /// <summary>
        /// Select 'Lê Vĩnh Khiêm' in 'cbKhachHang' combo box
        /// </summary>
        public string UICbKhachHangComboBoxSelectedItem = "Lê Vĩnh Khiêm";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestLan2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class TestLan2Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'White conc' in 'cboSanPham' combo box
        /// </summary>
        public string UICboSanPhamComboBoxSelectedItem = "White conc";
        
        /// <summary>
        /// Select '3' in 'cbSoLuong' combo box
        /// </summary>
        public string UICbSoLuongComboBoxSelectedItem = "3";
        
        /// <summary>
        /// Select 'Nguyễn Quang Huy' in 'cbKhachHang' combo box
        /// </summary>
        public string UICbKhachHangComboBoxSelectedItem = "Nguyễn Quang Huy";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestBuoc1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class TestBuoc1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'White conc' in 'cboSanPham' combo box
        /// </summary>
        public string UICboSanPhamComboBoxSelectedItem = "White conc";
        
        /// <summary>
        /// Select '1' in 'cbSoLuong' combo box
        /// </summary>
        public string UICbSoLuongComboBoxSelectedItem = "1";
        
        /// <summary>
        /// Select 'Lê Vĩnh Khiêm' in 'cbKhachHang' combo box
        /// </summary>
        public string UICbKhachHangComboBoxSelectedItem = "Lê Vĩnh Khiêm";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Buoc1Test'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class Buoc1TestParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'White conc' in 'cboSanPham' combo box
        /// </summary>
        public string UICboSanPhamComboBoxSelectedItem = "White conc";
        
        /// <summary>
        /// Select '1' in 'cbSoLuong' combo box
        /// </summary>
        public string UICbSoLuongComboBoxSelectedItem = "1";
        
        /// <summary>
        /// Select 'Phan Thanh Hải' in 'cbKhachHang' combo box
        /// </summary>
        public string UICbKhachHangComboBoxSelectedItem = "Phan Thanh Hải";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class TestValueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'txtTienTraKhach' text box is not equal to '0'
        /// </summary>
        public string UITxtTienTraKhachEditControlType = "0";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrmDangNhapWindow : WinWindow
    {
        
        public UIFrmDangNhapWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frmDangNhap";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frmDangNhap");
            #endregion
        }
        
        #region Properties
        public UIUsernameWindow UIUsernameWindow
        {
            get
            {
                if ((this.mUIUsernameWindow == null))
                {
                    this.mUIUsernameWindow = new UIUsernameWindow(this);
                }
                return this.mUIUsernameWindow;
            }
        }
        
        public UIPasswordWindow UIPasswordWindow
        {
            get
            {
                if ((this.mUIPasswordWindow == null))
                {
                    this.mUIPasswordWindow = new UIPasswordWindow(this);
                }
                return this.mUIPasswordWindow;
            }
        }
        
        public UIĐăngnhậpWindow UIĐăngnhậpWindow
        {
            get
            {
                if ((this.mUIĐăngnhậpWindow == null))
                {
                    this.mUIĐăngnhậpWindow = new UIĐăngnhậpWindow(this);
                }
                return this.mUIĐăngnhậpWindow;
            }
        }
        
        public WinClient UIFrmDangNhapClient
        {
            get
            {
                if ((this.mUIFrmDangNhapClient == null))
                {
                    this.mUIFrmDangNhapClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIFrmDangNhapClient.SearchProperties[WinControl.PropertyNames.Name] = "frmDangNhap";
                    this.mUIFrmDangNhapClient.WindowTitles.Add("frmDangNhap");
                    #endregion
                }
                return this.mUIFrmDangNhapClient;
            }
        }
        #endregion
        
        #region Fields
        private UIUsernameWindow mUIUsernameWindow;
        
        private UIPasswordWindow mUIPasswordWindow;
        
        private UIĐăngnhậpWindow mUIĐăngnhậpWindow;
        
        private WinClient mUIFrmDangNhapClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUsernameWindow : WinWindow
    {
        
        public UIUsernameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTaiKhoan";
            this.WindowTitles.Add("frmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTaiKhoanEdit
        {
            get
            {
                if ((this.mUITxtTaiKhoanEdit == null))
                {
                    this.mUITxtTaiKhoanEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTaiKhoanEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Đăng nhập";
                    this.mUITxtTaiKhoanEdit.WindowTitles.Add("frmDangNhap");
                    #endregion
                }
                return this.mUITxtTaiKhoanEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTaiKhoanEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPasswordWindow : WinWindow
    {
        
        public UIPasswordWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMatKhau";
            this.WindowTitles.Add("frmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMatKhauEdit
        {
            get
            {
                if ((this.mUITxtMatKhauEdit == null))
                {
                    this.mUITxtMatKhauEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMatKhauEdit.WindowTitles.Add("frmDangNhap");
                    #endregion
                }
                return this.mUITxtMatKhauEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMatKhauEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIĐăngnhậpWindow : WinWindow
    {
        
        public UIĐăngnhậpWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnDangNhap";
            this.WindowTitles.Add("frmDangNhap");
            #endregion
        }
        
        #region Properties
        public WinButton UIĐăngnhậpButton
        {
            get
            {
                if ((this.mUIĐăngnhậpButton == null))
                {
                    this.mUIĐăngnhậpButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIĐăngnhậpButton.SearchProperties[WinButton.PropertyNames.Name] = "Đăng nhập";
                    this.mUIĐăngnhậpButton.WindowTitles.Add("frmDangNhap");
                    #endregion
                }
                return this.mUIĐăngnhậpButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIĐăngnhậpButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIBánHàngWindow : WinWindow
    {
        
        public UIBánHàngWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Bán Hàng";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Bán Hàng");
            #endregion
        }
        
        #region Properties
        public WinButton UIBánHàngButton
        {
            get
            {
                if ((this.mUIBánHàngButton == null))
                {
                    this.mUIBánHàngButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBánHàngButton.SearchProperties[WinButton.PropertyNames.Name] = "Bán Hàng";
                    this.mUIBánHàngButton.WindowTitles.Add("Bán Hàng");
                    #endregion
                }
                return this.mUIBánHàngButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBánHàngButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIBánhàngWindow : WinWindow
    {
        
        public UIBánhàngWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "                                                       Bán hàng";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public UICboSanPhamWindow UICboSanPhamWindow
        {
            get
            {
                if ((this.mUICboSanPhamWindow == null))
                {
                    this.mUICboSanPhamWindow = new UICboSanPhamWindow(this);
                }
                return this.mUICboSanPhamWindow;
            }
        }
        
        public UICbSoLuongWindow UICbSoLuongWindow
        {
            get
            {
                if ((this.mUICbSoLuongWindow == null))
                {
                    this.mUICbSoLuongWindow = new UICbSoLuongWindow(this);
                }
                return this.mUICbSoLuongWindow;
            }
        }
        
        public UITHÊMVÀOGIỎWindow UITHÊMVÀOGIỎWindow
        {
            get
            {
                if ((this.mUITHÊMVÀOGIỎWindow == null))
                {
                    this.mUITHÊMVÀOGIỎWindow = new UITHÊMVÀOGIỎWindow(this);
                }
                return this.mUITHÊMVÀOGIỎWindow;
            }
        }
        
        public UICbKhachHangWindow UICbKhachHangWindow
        {
            get
            {
                if ((this.mUICbKhachHangWindow == null))
                {
                    this.mUICbKhachHangWindow = new UICbKhachHangWindow(this);
                }
                return this.mUICbKhachHangWindow;
            }
        }
        
        public UITẠMTÍNHWindow UITẠMTÍNHWindow
        {
            get
            {
                if ((this.mUITẠMTÍNHWindow == null))
                {
                    this.mUITẠMTÍNHWindow = new UITẠMTÍNHWindow(this);
                }
                return this.mUITẠMTÍNHWindow;
            }
        }
        
        public UIHóađơnGroup UIHóađơnGroup
        {
            get
            {
                if ((this.mUIHóađơnGroup == null))
                {
                    this.mUIHóađơnGroup = new UIHóađơnGroup(this);
                }
                return this.mUIHóađơnGroup;
            }
        }
        
        public UIItem0Window UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new UIItem0Window(this);
                }
                return this.mUIItem0Window;
            }
        }
        
        public UITẠOHÓAĐƠNXUẤTBILLWindow UITẠOHÓAĐƠNXUẤTBILLWindow
        {
            get
            {
                if ((this.mUITẠOHÓAĐƠNXUẤTBILLWindow == null))
                {
                    this.mUITẠOHÓAĐƠNXUẤTBILLWindow = new UITẠOHÓAĐƠNXUẤTBILLWindow(this);
                }
                return this.mUITẠOHÓAĐƠNXUẤTBILLWindow;
            }
        }
        
        public UITxtMoTaWindow UITxtMoTaWindow
        {
            get
            {
                if ((this.mUITxtMoTaWindow == null))
                {
                    this.mUITxtMoTaWindow = new UITxtMoTaWindow(this);
                }
                return this.mUITxtMoTaWindow;
            }
        }
        
        public UIItem0Window1 UIItem0Window1
        {
            get
            {
                if ((this.mUIItem0Window1 == null))
                {
                    this.mUIItem0Window1 = new UIItem0Window1(this);
                }
                return this.mUIItem0Window1;
            }
        }
        #endregion
        
        #region Fields
        private UICboSanPhamWindow mUICboSanPhamWindow;
        
        private UICbSoLuongWindow mUICbSoLuongWindow;
        
        private UITHÊMVÀOGIỎWindow mUITHÊMVÀOGIỎWindow;
        
        private UICbKhachHangWindow mUICbKhachHangWindow;
        
        private UITẠMTÍNHWindow mUITẠMTÍNHWindow;
        
        private UIHóađơnGroup mUIHóađơnGroup;
        
        private UIItem0Window mUIItem0Window;
        
        private UITẠOHÓAĐƠNXUẤTBILLWindow mUITẠOHÓAĐƠNXUẤTBILLWindow;
        
        private UITxtMoTaWindow mUITxtMoTaWindow;
        
        private UIItem0Window1 mUIItem0Window1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICboSanPhamWindow : WinWindow
    {
        
        public UICboSanPhamWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboSanPham";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboSanPhamComboBox
        {
            get
            {
                if ((this.mUICboSanPhamComboBox == null))
                {
                    this.mUICboSanPhamComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboSanPhamComboBox.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUICboSanPhamComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboSanPhamComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICbSoLuongWindow : WinWindow
    {
        
        public UICbSoLuongWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbSoLuong";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICbSoLuongComboBox
        {
            get
            {
                if ((this.mUICbSoLuongComboBox == null))
                {
                    this.mUICbSoLuongComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICbSoLuongComboBox.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUICbSoLuongComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICbSoLuongComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITHÊMVÀOGIỎWindow : WinWindow
    {
        
        public UITHÊMVÀOGIỎWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnThemVaoGio";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinButton UITHÊMVÀOGIỎButton
        {
            get
            {
                if ((this.mUITHÊMVÀOGIỎButton == null))
                {
                    this.mUITHÊMVÀOGIỎButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITHÊMVÀOGIỎButton.SearchProperties[WinButton.PropertyNames.Name] = "THÊM VÀO GIỎ";
                    this.mUITHÊMVÀOGIỎButton.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITHÊMVÀOGIỎButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITHÊMVÀOGIỎButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICbKhachHangWindow : WinWindow
    {
        
        public UICbKhachHangWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cbKhachHang";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICbKhachHangComboBox
        {
            get
            {
                if ((this.mUICbKhachHangComboBox == null))
                {
                    this.mUICbKhachHangComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICbKhachHangComboBox.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUICbKhachHangComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICbKhachHangComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITẠMTÍNHWindow : WinWindow
    {
        
        public UITẠMTÍNHWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnTamTinh";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinButton UITẠMTÍNHButton
        {
            get
            {
                if ((this.mUITẠMTÍNHButton == null))
                {
                    this.mUITẠMTÍNHButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITẠMTÍNHButton.SearchProperties[WinButton.PropertyNames.Name] = "TẠM TÍNH";
                    this.mUITẠMTÍNHButton.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITẠMTÍNHButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITẠMTÍNHButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIHóađơnGroup : WinGroup
    {
        
        public UIHóađơnGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Hóa đơn";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem0Window
        {
            get
            {
                if ((this.mUIItem0Window == null))
                {
                    this.mUIItem0Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Name] = "0";
                    this.mUIItem0Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIItem0Window.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUIItem0Window.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUIItem0Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem0Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItem0Window : WinWindow
    {
        
        public UIItem0Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtKhachThanhToan";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtKhachThanhToanEdit
        {
            get
            {
                if ((this.mUITxtKhachThanhToanEdit == null))
                {
                    this.mUITxtKhachThanhToanEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtKhachThanhToanEdit.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITxtKhachThanhToanEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtKhachThanhToanEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITẠOHÓAĐƠNXUẤTBILLWindow : WinWindow
    {
        
        public UITẠOHÓAĐƠNXUẤTBILLWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnTaoHoaDon";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinButton UITẠOHÓAĐƠNXUẤTBILLButton
        {
            get
            {
                if ((this.mUITẠOHÓAĐƠNXUẤTBILLButton == null))
                {
                    this.mUITẠOHÓAĐƠNXUẤTBILLButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITẠOHÓAĐƠNXUẤTBILLButton.SearchProperties[WinButton.PropertyNames.Name] = "TẠO HÓA ĐƠN & XUẤT BILL";
                    this.mUITẠOHÓAĐƠNXUẤTBILLButton.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITẠOHÓAĐƠNXUẤTBILLButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITẠOHÓAĐƠNXUẤTBILLButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtMoTaWindow : WinWindow
    {
        
        public UITxtMoTaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMoTa";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMoTaEdit
        {
            get
            {
                if ((this.mUITxtMoTaEdit == null))
                {
                    this.mUITxtMoTaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMoTaEdit.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITxtMoTaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMoTaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItem0Window1 : WinWindow
    {
        
        public UIItem0Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTienTraKhach";
            this.WindowTitles.Add("                                                       Bán hàng");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTienTraKhachEdit
        {
            get
            {
                if ((this.mUITxtTienTraKhachEdit == null))
                {
                    this.mUITxtTienTraKhachEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTienTraKhachEdit.WindowTitles.Add("                                                       Bán hàng");
                    #endregion
                }
                return this.mUITxtTienTraKhachEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTienTraKhachEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIThôngbáoWindow : WinWindow
    {
        
        public UIThôngbáoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Thông báo !!!";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Thông báo !!!");
            #endregion
        }
        
        #region Properties
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Thông báo !!!");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Thông báo !!!");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrm_ChonTienWindow : WinWindow
    {
        
        public UIFrm_ChonTienWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frm_ChonTien";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frm_ChonTien");
            #endregion
        }
        
        #region Properties
        public UIKháchĐưaĐủWindow UIKháchĐưaĐủWindow
        {
            get
            {
                if ((this.mUIKháchĐưaĐủWindow == null))
                {
                    this.mUIKháchĐưaĐủWindow = new UIKháchĐưaĐủWindow(this);
                }
                return this.mUIKháchĐưaĐủWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIKháchĐưaĐủWindow mUIKháchĐưaĐủWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIKháchĐưaĐủWindow : WinWindow
    {
        
        public UIKháchĐưaĐủWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnKhachDuaDu";
            this.WindowTitles.Add("frm_ChonTien");
            #endregion
        }
        
        #region Properties
        public WinButton UIKháchĐưaĐủButton
        {
            get
            {
                if ((this.mUIKháchĐưaĐủButton == null))
                {
                    this.mUIKháchĐưaĐủButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIKháchĐưaĐủButton.SearchProperties[WinButton.PropertyNames.Name] = "Khách Đưa Đủ";
                    this.mUIKháchĐưaĐủButton.WindowTitles.Add("frm_ChonTien");
                    #endregion
                }
                return this.mUIKháchĐưaĐủButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIKháchĐưaĐủButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrm_HoaDonWindow : WinWindow
    {
        
        public UIFrm_HoaDonWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "frm_HoaDon";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("frm_HoaDon");
            #endregion
        }
        
        #region Properties
        public UIXuấtBillWindow UIXuấtBillWindow
        {
            get
            {
                if ((this.mUIXuấtBillWindow == null))
                {
                    this.mUIXuấtBillWindow = new UIXuấtBillWindow(this);
                }
                return this.mUIXuấtBillWindow;
            }
        }
        
        public UIFrm_HoaDonTitleBar UIFrm_HoaDonTitleBar
        {
            get
            {
                if ((this.mUIFrm_HoaDonTitleBar == null))
                {
                    this.mUIFrm_HoaDonTitleBar = new UIFrm_HoaDonTitleBar(this);
                }
                return this.mUIFrm_HoaDonTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIXuấtBillWindow mUIXuấtBillWindow;
        
        private UIFrm_HoaDonTitleBar mUIFrm_HoaDonTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIXuấtBillWindow : WinWindow
    {
        
        public UIXuấtBillWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnXuatBill";
            this.WindowTitles.Add("frm_HoaDon");
            #endregion
        }
        
        #region Properties
        public WinButton UIXuấtBillButton
        {
            get
            {
                if ((this.mUIXuấtBillButton == null))
                {
                    this.mUIXuấtBillButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIXuấtBillButton.SearchProperties[WinButton.PropertyNames.Name] = "Xuất Bill";
                    this.mUIXuấtBillButton.WindowTitles.Add("frm_HoaDon");
                    #endregion
                }
                return this.mUIXuấtBillButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIXuấtBillButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFrm_HoaDonTitleBar : WinTitleBar
    {
        
        public UIFrm_HoaDonTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("frm_HoaDon");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("frm_HoaDon");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
